// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj9-jSWRNqm8MGv3xkeEZpHQi-HrgbNLY',
    appId: '1:865024567164:web:9fa0a4198eddffd1b926f9',
    messagingSenderId: '865024567164',
    projectId: 'fir-practice-7e1dc',
    authDomain: 'fir-practice-7e1dc.firebaseapp.com',
    storageBucket: 'fir-practice-7e1dc.appspot.com',
    measurementId: 'G-QH4CBB9J3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5GxWaqwB5OLnfgFfKz0Mlqy-3olbNdwk',
    appId: '1:865024567164:android:07c828da52d11a64b926f9',
    messagingSenderId: '865024567164',
    projectId: 'fir-practice-7e1dc',
    storageBucket: 'fir-practice-7e1dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU5cuq-MQLIQf-b5HMNf267Y1NSRYK6ww',
    appId: '1:865024567164:ios:6c9ee28706bcd884b926f9',
    messagingSenderId: '865024567164',
    projectId: 'fir-practice-7e1dc',
    storageBucket: 'fir-practice-7e1dc.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU5cuq-MQLIQf-b5HMNf267Y1NSRYK6ww',
    appId: '1:865024567164:ios:290d7c98e47fd5e9b926f9',
    messagingSenderId: '865024567164',
    projectId: 'fir-practice-7e1dc',
    storageBucket: 'fir-practice-7e1dc.appspot.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
